#!/bin/bash

main() {
  echo "running pre-commit hooks..."

  git stash -q --keep-index
  rake
  local rake_status=$?
  git stash pop -q

  if [[ "${rake_status}" != "0" ]]; then
    echo "Rake failed! Fix those errors before commiting and make sure you've" \
      "staged all changes needed!"
    exit 1
  fi

  echo "pre-commit hooks done!"
}

main
