---
version: "2"
plugins:
  duplication:
    enabled: true
    exclude_paths:
    - lib/pwnlib/shellcraft/generators/
    - test/
checks:
  method-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 10
exclude_patterns:
- "test/"
