AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Encoding:
  Enabled: false

Style/EndOfLine:
  EnforcedStyle: lf

Style/IndentHeredoc:
  Enabled: false

# TODO(Darkpi):
#   Enable this when rubocop fix the setter methods being reported.
#   (https://github.com/bbatsov/rubocop/issues/4152)
# Style/MethodCallWithArgsParentheses:
#   Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true
